spring.application.name=ecom-application
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb?options=-c%20TimeZone=Asia/Kolkata
server.port=8080


spring.datasource.username=sCode
spring.datasource.password=sCode

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

management.endpoint.shutdown.access=unrestricted
server.shutdown=graceful

info.app.name=E-Commerce Application
info.app.version=1.0.0
info.app.description=Spring Boot E-Commerce Project
info.app.author=Mickey